mysite/apps/polls/urls.py
from django.urls import path

from . import views

app_name = 'articles'
urlpatterns = [
	path('', views.index, name = 'index'),
	path('keys/', views.keys, name = 'keys'),
	path('create_article/', views.create_article, name = 'create_article'),
	path('register/', views.register, name = 'register'),
	path('logingin/', views.logingin, name = 'logingin'),
	path('logingout/', views.logingout, name = 'logingout'),
	path('<int:article_id>/', views.detail, name = 'detail'),
	path('<int:article_id>/leave_comment/', views.leave_comment, name = 'leave_comment'),
	path('<int:article_id>/leave_like/', views.leave_like, name = 'leave_like'),
	path('<int:article_id>/leave_dislike/', views.leave_dislike, name = 'leave_dislike'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
]

mysite/apps/polls/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.utils import timezone, dateformat

class Article(models.Model):
	article_author = models.ForeignKey(User, default=0, blank=True, null=False, on_delete=models.CASCADE, related_name='article_author_user')
	article_title = models.CharField('article name', max_length = 200)
	article_text = models.TextField('article text')
	ppub_date = models.DateTimeField('pub date')
	liked = models.ManyToManyField(User, default=None, blank=True)

	def __str__(self):
		return self.article_title

	def was_recent(self):
		return self.ppub_date >= (timezone.now() - datetime.timedelta(days = 7))

	@property
	def num_likes(self):
		return self.liked.all().count()


LIKE_CHOISE = ( ('Like', 'Like'), ('Unlike', 'Unlike') )

class Like(models.Model):
	user = models.ForeignKey(User, on_delete = models.CASCADE)
	article = models.ForeignKey(Article, on_delete = models.CASCADE)
	val = models.CharField(choices=LIKE_CHOISE, default='like', max_length=10)
	
	def __str__(self):
		return str(self.article)

class Comment(models.Model):
	article = models.ForeignKey(Article, on_delete = models.CASCADE)
	author_name = models.CharField('author name', max_length = 50)
	comment_text = models.CharField('comment text', max_length = 200)

	def __str__(self):
		return self.author_name

	def get_time_com():
		return dateformat.format(timezone.now(), 'Y-m-d H:i:s')

mysite/apps/polls/views.py
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponseRedirect
import datetime
from django.utils import timezone, dateformat
from .models import Article, Comment, Like, User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.urls import reverse

def index(request):
	latest_articles = Article.objects.order_by('-ppub_date')
	return render(request, 'articles/list.html', {'latest_articles': latest_articles});

def register(request):
	form = UserCreationForm()

	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect( reverse('articles:index') )

	cont = {'form' : form}
	return render(request, 'articles/register.html', cont)

def logingin(request):
	username = request.POST['username']
	password = request.POST['psswrd']
	user = authenticate(username=username, password=password)
	if user is not None:
		if user.is_active:
			login(request, user)
			return HttpResponseRedirect( request.META.get('HTTP_REFERER') )
        	# return HttpResponseRedirect( reverse('articles:index'))
		else:
			messages.info(request, "This user is blocked")
			return HttpResponseRedirect( request.META.get('HTTP_REFERER')) 

	else:
		messages.info(request, "Wrong user/password data")
		return HttpResponseRedirect( request.META.get('HTTP_REFERER') )


def logingout(request):
    logout(request)
    return HttpResponseRedirect( reverse('articles:index'))


def create_article(request):

	if request.method == 'POST' and len(request.POST['article_title']) in range(1, 200):
		if 'anon_article' not in request.POST:
			a = Article(article_text = request.POST['article_text'], article_title = request.POST['article_title'], article_author = request.user, ppub_date = dateformat.format(timezone.now(), 'Y-m-d H:i:s'))
			a.save()
		else:
			a = Article(article_text = request.POST['article_text'], article_title = request.POST['article_title'], article_author = User.objects.get(id = 0), ppub_date = dateformat.format(timezone.now(), 'Y-m-d H:i:s'))
			a.save()
		return redirect( reverse('articles:index') )

	return render(request, 'articles/create_article.html')


def detail(request, article_id):
	try:
	 	a = Article.objects.get(id = article_id)
	 	user = request.user
	except:
		raise Http404("Хммм похоже такого тут нету...")

	latest_comments_list = a.comment_set.order_by('-id')

	return render(request, 'articles/detail.html', {'article': a, 'latest_comments_list': latest_comments_list, 'user' : user})

def keys(request):
	key_words = request.POST['key_words'].split()
	q = ' OR '.join(["article_text LIKE %s" for i in key_words])
	n = ['%%' + i + '%%' for i in key_words]
	matching_articles = Article.objects.raw("SELECT * FROM polls_article WHERE " + q, n)
	print(matching_articles)
	return render(request, 'articles/keys.html', {'matching_articles': matching_articles});

def leave_comment(request, article_id):
	try:
	 	a = Article.objects.get(id = article_id)
	except:
	 	raise Http404("Хммм похоже такого тут нету...")

	if request.user.is_authenticated:
		username = request.user.username

	txt = request.POST['text'].replace('!time', str(Comment.get_time_com()) ) 
	
	a.comment_set.create(author_name = username, comment_text = txt)

	return HttpResponseRedirect( reverse('articles:detail', args = (a.id,)) )

def leave_like(request, article_id):
	try:
	 	a = Article.objects.get(id = article_id)
	 	user = request.user
	except:
	 	raise Http404("Хммм похоже такого тут нету...")

	if request.method == 'POST':
		if user in a.liked.all():
			a.liked.remove(user)
		else:
			a.liked.add(user)

		like, created = Like.objects.get_or_create(user=user, article=a)

		if not created:
			if like.val == 'Like':
				like.val = 'Unlike'
			else:
				like.val = 'Like'


		like.save()

	return HttpResponseRedirect( reverse('articles:detail', args = (a.id,)) )

def leave_dislike(request, article_id):
	try:
	 	a = Article.objects.get(id = article_id)
	except:
	 	raise Http404("Хммм похоже такого тут нету...")

	if 'dislike' not in request.GET:
		raise Http404("Хммм жопа")
	else: 
		a.dislikes = a.dislikes + 1
		a.save() 

	return HttpResponseRedirect( reverse('articles:detail', args = (a.id,)) )

mysite/templates/articles/create_article.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Написать свою статью {% endblock %}

{% block content %}	

<header class="sticky-top">

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<a class="navbar-brand" href="{% url 'articles:index' %}">/ < вернутся к списку статей /</a>
		<div class="blank col"></div>
		<h1>/Polls/ <small>Just post articles</small></h1>
	</nav>

</header>

<div class="content-top p-2 mb-1">
	<h2 class="text-center">Добавление статьи</h2>
</div>

<div class="content container form-group">

	<form action="{% url 'articles:create_article' %}" method="POST">

		{% csrf_token %}
		<div class="text-left row">
			<label class="col" for="article_title">Название статьи</label>
			<small class="text-right col">200 букв максимум</small>
		</div>
		<input class="form-control" type="text" name="article_title" maxlength="200">
		<br>

		<div class="custom-control custom-switch">
			<input type="checkbox" name="anon_article" class="custom-control-input" id="switch1">
			<label class="custom-control-label" for="switch1">Я хочу чтобы статья была анонимной </label>
		</div>

<!-- 		<div>
			<label for="anon_article">Хотите чтобы статья была анонимной? </label>
			<input type="checkbox" name="anon_article">
		</div> -->
		<br>
		<label for="article_text">Текст статьи</label>
		<br>
		<textarea class="form-control" name="article_text" cols="60" rows="20"></textarea>
		<br>
		<button class="form-control btn btn-primary" type="submit">Опубликовать</button>	

	</form>
</div>
{% endblock %}

mysite/templates/articles/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{article.article_title}} {% endblock %}

{% block content %}

<header class="sticky-top">

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<a class="navbar-brand" href="{% url 'articles:index' %}">/ < вернутся к списку статей /</a>
		<button class="navbar-toggler text-left" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item">
					<a class="nav-link" href="#">Статья</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#comments">Коментарии</a>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link" href="#leave_comment">Оставить коментарий</a>
				</li>
			</ul>
			
		</div>
		<h1>/Polls/ <small>Just post articles</small></h1>
	</nav>

</header>

<!-- <a class="btn btn-dark" href="{% url 'articles:index' %}"> <<< Вернутся к списку статей</a> -->
<div class="article-top">

	<h1 class="text-center p-2">{{article.article_title}}</h1>

</div>

<hr>
<div class="article p-2">

<i>Автор: {{article.article_author}}</i>

<hr>

<div class="content">

	<pre id="a_content">{{article.article_text|safe}} </pre>

</div>


<div class="date">

	<em>{{article.ppub_date}}</em>

	{% if article.was_recent %}

		<sub><b>СВЕЖАК</b></sub>

	{% else %}

		<sub><b>НЕ СВЕЖАК</b></sub>

	{% endif %}

</div>	

</div>

<div id="forms" class="like-dislike m-2">
	<form action="{% url 'articles:leave_like' article.id %}" method="POST">

		{% csrf_token %}

		<label for="like">Нравится: {{article.liked.all.count}}</label>

		{% if user.is_authenticated %}

		{% if user not in article.liked.all %}

		<button class="btn btn-success btn-sm" type="submit" name="like" value="1">Лайк</button>

		{% else %}

		<button class="btn btn-danger btn-sm" type="submit" name="unlike" value="1">Забрать Лайк</button>

		{% endif %}

		{% else %}

		{% endif %}

	</form>
<!-- <strong>|</strong>
	<form action="{% url 'articles:leave_dislike' article.id %}" method="GET">

		{% csrf_token %}

		<label for="like">Кринжануло: {{article.dislikes}}</label>
		<button type="submit" name="dislike" value="1">Кринж</button>

	</form> -->
</div>


<div id="comments" class="p-2 mt-3">

	<h3>Коментарии:</h3>
	<hr>

	{% if latest_comments_list %}
	
	{% for c in latest_comments_list %}

		<p class="ml-4 "> <strong>{{c.author_name}}:</strong> {{c.comment_text}}</p>

	{% endfor %}

	{% else %}
	<i>А коментарив то нет. Пишите первым.</i> 
	{% endif %}

</div>

<hr>

<div id="leave_comment">

	{% if user.is_authenticated %}
	
	<h4>Оставить коментарий</h4>
<div class="send-comment form-group">
	<form action="{% url 'articles:leave_comment' article.id %}" method="POST">

		{% csrf_token %}

		<textarea class="form-control" name="text" required="" placeholder="Ваш комнтарий" cols="20" rows="5" maxlength="200"></textarea>
		<br>
		<button class="form-control btn btn-primary" type="submit">Запостить</button>

	</form>
</div>
	{% else %}

	<p>Вам нужно ввойти в аккаунт чтобы оставить коментарий или поставить Лайк</p>

	<form action="{% url 'articles:logingin' %}" method="POST">

		{% csrf_token %}

		<input type="text" name="username">
		<input type="password" name="psswrd">
		<input type="submit" value="Login">

	</form>

	{% endif %}

	
</div>

<!-- <style>

	form {
		display: inline-block;
	}
	
	#forms{
		display: inline-block;
	}	

	#a_content{
		font: normal normal 400 16px serif;
	}

</style> -->

{% endblock %}

mysite/templates/articles/keys.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>Результаты</title>
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link type="text/css" rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>

<h1>Результаты</h1>
{% if matching_articles %}

		{% for a in matching_articles %}
			<a class="btn btn-dark btn-block btn-lg text-left" href="{% url 'articles:detail' a.id %}">/{{a.id}}/ {{a.article_title}}</a>
			<br>
		{% endfor %}

	{% else %}
		<p>Статьей нету...</p>
	{% endif %}

<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

mysite/templates/articles/list.html
{% extends 'base.html' %}

{% block title %} Последние статьи {% endblock %}
{% load static %}

{% block content %}

<header class="sticky-top">

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<a class="navbar-brand" href="#">///</a>
		<button class="navbar-toggler text-left" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item active">
					<a class="nav-link" href="#">Главная</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#write">Написать</a>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link" href="#find">Поиск</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#article_list">Статьи</a>
				</li>
			</ul>
			
		</div>
		<h1>/Polls/ <small>Just post articles</small></h1>
	</nav>
	
</header>

<div class="register-login-logout row p-3">
	<div class="blank col-2"></div>
	<h4 class="col-sm p-1 text-center my-auto">Здарова, {{ user.username|default:'Гость' }}! </h4>

	{% if user.is_authenticated %}

	<a class="btn btn-outline-danger col-2" href="{% url 'articles:logingout' %}">Выйти</a>
	
	{% else %}

	<button class="btn btn-outline-danger col-2 float-right" data-toggle="collapse" data-target="#login-register">Регистрация | Войти </button>

	<div id="login-register" class="collapse col-2 float-right">
		<div class="login text-center">
			<div class="form-group m-0">
				<form action="{% url 'articles:logingin' %}" method="POST" name="loginform">

					{% csrf_token %}

					<input class="form-control" type="text" name="username" placeholder="Логин">
					<input class="form-control" type="password" name="psswrd" placeholder="Пароль">
					<input class="form-control btn btn-primary" type="submit" value="Войти">

				</form>
			</div>	

			<p class="m-1">или</p>

			<a class="btn btn-outline-success" href="{% url 'articles:register' %}">Зарегистрироватся</a>
		</div>
	</div>

	{% if messages %}
	<div class="error-messages col-4 text-center my-auto">
		<div class="alert alert-success p-0 m-0">
			{% for message in messages %}

			<strong {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</strong>

			{% endfor %}
		</div>
	</div>
	{% endif %}

	{% endif %}

</div>

<hr>

<div class="main container">

	<div id="write" class="write text-center p-2">

		<h2>Хочешь написать свою статью?</h2>

		{% if user.is_authenticated %}

		<a class="btn btn-primary" href="{% url 'articles:create_article' %}">Добавить статью</a>

		{% else %}

		<p>А вот если хочешь, то сначало ввойди в аккаунт или зарегистрируйся</p>

		{% endif %}
	</div>
	<hr>

	<div id="find" class="find p-2">
		<h4>Найти статьи по ключевым словам</h4>
		<div class="form-group m-0">

			<form action="{% url 'articles:keys' %}" method="POST">

				{% csrf_token %}	

				<div class="input-group mb-3">
					<input type="text" class="form-control" name="key_words" placeholder="интересно круто познавательно">
					<div class="input-group-append">
						<input class="btn btn-success" type="submit" name="search" value="Найти">
					</div>
				</div>

			</form>
		</div>
	</div>

	<div id="article_list" class="articles">

		<h2 class="mb-3">Статьи</h2>

		{% if latest_articles %}
		<div class="article-table">
			{% for a in latest_articles %}
			<a class="btn btn-dark btn-block btn-lg text-left" href="{% url 'articles:detail' a.id %}">/{{a.id}}/  {{a.article_title}}</a>
			<br>
			{% endfor %}
		</div>
		{% else %}
		<p>Статьей нету...</p>
		<style>
			#article_list	{
				background-image: url({% static 'png/logo.png' %});
				height: 360px; /* You must set a specified height */
				background-position: center;
				background-repeat: no-repeat; /* Do not repeat the image */
				background-size: cover; /* Resize the background image to cover the entire container */
			}
		</style>
		{% endif %}
	</div>

</div>


{% endblock %}

mysite/templates/articles/register.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>Регистрация</title>
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link type="text/css" rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>

	<div id="register_form"  class="container text-center form-group">
		<h2 class="mt-4 p-2 text-right">Регистрация</h2>
		<form class="mx-auto" action="" method="POST">
			
			{% csrf_token %}

			<div  class="text-left row">
				<label class="col" for="username">Логин</label>
				<small class="text-right col">150 букв максимум</small>
			</div>

			<input class="form-control" type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus="" required="" id="id_username">

			<br>

			<div  class="text-left">
				<label class="text-left" for="password1">Пароль</label>
			</div>

			<input class="form-control" type="password" name="password1" autocomplete="new-password" required="" id="id_password1">
			<small>Требования к паролю:</small>
			<span class="badge badge-pill badge-warning">8 символов как минимум</span>
			<span class="badge badge-pill badge-warning">Надёжный</span>
			<span class="badge badge-pill badge-warning">Не послностью числовой</span>

			<br>

			<div  class="text-left">
				<label class="text-left" for="password2">Подтверждение пароля</label>
			</div>

			<input class="form-control" type="password" name="password2" autocomplete="new-password" required="" id="id_password2">

			<br>

			<button class="form-control btn btn-success" type="submit" name="Create User"> Зарегистрироватся </button>

		</form>
	</div>

	<a class="btn btn-dark" href="{% url 'articles:index' %}">/ Отменить регистрацию /</a>

	<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

<!-- Required. 150 букв максимум. Letters, digits and @/./+/-/_ only. -->

<!-- <ul><li>Your password can’t be too similar to your other personal information.</li><li>8 символов как минимум.</li><li>Надёжный</li><li>Не послностью числовой.</li></ul> -->

mysite/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>{% block title %} Мой сайт {% endblock %}</title>
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link type="text/css" rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
	
	{% block content %}{% endblock %}

	<footer id="footer" class="text-center">
		<div class="row justify-content-center p-3">
			<div class="col-6">
				<h2>Причина существования</h2>
				<small>Этот сайт создан с целью демонстрирования практических умений применения фреймворка <a href="https://youtu.be/OhlVBpEnjig?t=6">Django</a></small>
			</div>

			<div class="contacts col-6 text-center">
				<h3>Контакты</h3>
				<ul style="list-style: none;">
					<li><a class="text-dark" href="tel:+380968131709">+380 (96) 813-17-09</a></li>
					<li><a class="text-dark" href="mailto:daniil.zakharov@nure.ua">daniil.zakharov@nure.ua</a></li>
				</ul>
			</div>
		</div>
		<div class="text-left container">
			<p class="m-0">© 2021 - ∞ articleboard "/Polls/"</p>
			<!-- <a style="font-size: 6px; color: #f1f1f1" href="#footer">Анекдот</a> -->
		</div>
	</footer>

	<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>